name: pypy-esnow
version: 0.1
summary: PyPy is a fast, compliant alternative implementation of the Python language.
description: |
    PyPy is a fast, compliant alternative implementation of the Python language.
confinement: strict

apps:
    pypy-esnow:
        command: pypy
        plugs:
            - network
            - network-bind
    #pypy3:
    #    command: pypy3
    #    plugs:
    #        - network
    #        - network-bind

parts:
    pypy-tip:
        plugin: pypy
        install-via: prefix
        source: https://bitbucket.org/pypy/pypy
        source-type: hg
        source-branch: release-5.x
        #source-branch: default
        build-packages:
    #pypy3:
    #    plugin: pypy
    #    install-via: prefix
    #    source: https://bitbucket.org/pypy/pypy
    #    source-type: hg
    #    source-branch: release-pypy3.3-v5
    #    source-branch: py3.5
    #    #source-branch: py3.5-async
    #    build-packages:
